name: Website Automated Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 9 * * *'

jobs:
  test-website:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        npm init -y
        npm install puppeteer jest lighthouse chrome-launcher
    
    - name: Run Website Tests
      run: |
        node tests/website-tests.js
    
    - name: Run Lighthouse Performance Test
      run: |
        node tests/lighthouse-test.js
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/
