# GitHub Actions Workflow for Spring Associates Website Testing
# File: .github/workflows/website-tests.yml

name: Website Automated Tests

# When to run tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run tests daily at 9 AM UTC
    - cron: '0 9 * * *'

jobs:
  test-website:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        npm init -y
        npm install puppeteer jest lighthouse
    
    - name: Run Website Tests
      run: |
        node tests/website-tests.js
    
    - name: Run Lighthouse Performance Test
      run: |
        node tests/lighthouse-test.js
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: test-results/
